module.exports = {
	"react/display-name": "warn",
	"react/forbid-prop-types": "off",
	"react/no-danger": "error",
	"react/no-deprecated": "warn",
	"react/no-did-mount-set-state": ["warn"],
	"react/no-did-update-set-state": ["warn"],
	"react/no-direct-mutation-state": "error",
	"react/no-is-mounted": "error",
	"react/no-multi-comp": "warn",
	"react/no-set-state": "off",
	"react/no-string-refs": "error",
	"react/no-unknown-property": "warn",
	"react/prefer-es6-class": "off",
	"react/prefer-stateless-function": "warn",
	"react/prop-types": "off",
	"react/react-in-jsx-scope": "warn",
	"react/require-extension": "off",
	"react/require-render-return": "error",
	"react/self-closing-comp": "warn",
	"react/sort-comp": "warn",
	"react/sort-prop-types": ["error", { "ignoreCase": true, "callbacksLast": true, "requiredFirst": true}],
	"react/wrap-multilines": "warn"
};
