module.exports = {
    "arrow-body-style": ["warn", "as-needed"],
    "arrow-parens": ["warn", "always"],
    "arrow-spacing": ["warn", {"before": true, "after": true}],
    "constructor-super": "error",
    "generator-star-spacing": ["error", {"before": false, "after": true}],
    "no-class-assign": "error",
    "no-confusing-arrow": "off",
    "no-const-assign": "error",
    "no-dupe-class-members": "error",
    "no-duplicate-imports": ["error", { includeExports: true }],
    "no-new-symbol": "error",
    "no-restricted-imports": "off",
    "no-this-before-super": "error",
    "no-useless-constructor": "warn",
    "no-var": "warn",
    "object-shorthand": ["warn", "always"],
    "prefer-arrow-callback": "warn",
    "prefer-const": "off",
    "prefer-reflect": "off",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "prefer-template": "warn",
    "require-yield": "error",
    "sort-imports": "off",
    "template-curly-spacing": ["error", "never"],
    "yield-star-spacing": ["error", "after"]
};
